/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GettingStarted: typeof import('./src/components/GettingStarted.vue')['default']
    'IHeroicons:document': typeof import('~icons/heroicons/document')['default']
    'IHeroicons:documentSolid': typeof import('~icons/heroicons/document-solid')['default']
    'IHeroicons:square2Stack': typeof import('~icons/heroicons/square2-stack')['default']
    ImageItems: typeof import('./src/components/ImageItems.vue')['default']
    'IMynaui:terminalSolid': typeof import('~icons/mynaui/terminal-solid')['default']
    Lnb: typeof import('./src/components/Lnb.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
