/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoPlay: typeof import('./src/components/AutoPlay.vue')['default']
    AutoPlayDuration: typeof import('./src/components/AutoPlayDuration.vue')['default']
    Contents: typeof import('./src/components/Contents.vue')['default']
    DisableOnInteraction: typeof import('./src/components/DisableOnInteraction.vue')['default']
    DocIntro: typeof import('./src/components/docItems/DocIntro.vue')['default']
    DocItem: typeof import('./src/components/docItems/DocItem.vue')['default']
    DocItemType: typeof import('./src/components/docItems/DocItemType.vue')['default']
    DynamicBullets: typeof import('./src/components/DynamicBullets.vue')['default']
    EffectFade: typeof import('./src/components/EffectFade.vue')['default']
    GettingStarted: typeof import('./src/components/GettingStarted.vue')['default']
    'IHeroicons:codeBracketSquare': typeof import('~icons/heroicons/code-bracket-square')['default']
    'IHeroicons:codeBracketSquare16': typeof import('~icons/heroicons/code-bracket-square16')['default']
    'IHeroicons:codeBracketSquare16Solid': typeof import('~icons/heroicons/code-bracket-square16-solid')['default']
    'IHeroicons:document': typeof import('~icons/heroicons/document')['default']
    'IHeroicons:documentSolid': typeof import('~icons/heroicons/document-solid')['default']
    'IHeroicons:square2Stack': typeof import('~icons/heroicons/square2-stack')['default']
    ImageItems: typeof import('./src/components/ImageItems.vue')['default']
    'IMynaui:terminalSolid': typeof import('~icons/mynaui/terminal-solid')['default']
    KeyboardControl: typeof import('./src/components/KeyboardControl.vue')['default']
    Lnb: typeof import('./src/components/Lnb.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    PauseOnMouseEnter: typeof import('./src/components/PauseOnMouseEnter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scrollbar: typeof import('./src/components/Scrollbar.vue')['default']
    ShowNextButton: typeof import('./src/components/ShowNextButton.vue')['default']
    ShowPrevButton: typeof import('./src/components/ShowPrevButton.vue')['default']
    SideBar: typeof import('./src/components/docItems/sideBar.vue')['default']
    StopOnLastSlide: typeof import('./src/components/StopOnLastSlide.vue')['default']
  }
}
